languageCode = "en"
languageName = "English"
weight = 1
title = "Mordecai Kipng'etich"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  description = "Personal Website and Blog | Mordecai Kipng'etich"
  copyright = "No Rights Reserved"

[author]
  name = "Mordecai Kipng'etich"
  image = "img/profile.png"
  headline = "Software Developer • Open-Source Enthusiast"
  bio = "not from Regular Show"
  links = [
    { email = "mailto:contact@insidemordecai.com"},
    { twitter = "https://twitter.com/insidemordecai" },
    { github = "https://github.com/insidemordecai" },
    # { spotify = "https://open.spotify.com/user/jv19tenfbkqd9so7369kfvwxa?si=29415d195d8d41f4"},
    { linkedin = "https://www.linkedin.com/in/insidemordecai" },
    { goodreads = "https://www.goodreads.com/insidemordecai"}
  ]
