languageCode = "en"
languageName = "English"
weight = 1
title = "Mordecai Kipng'etich"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.svg"
  secondaryLogo = "img/secondaryLogo.svg"
  description = "Personal Website and Blog | Mordecai Kipng'etich"
  copyright = "[CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) - Mordecai Kipng'etich"
