# -- Theme Options --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "009BAD"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true 
enableSearch = true
enableCodeCopy = true
replyByEmail = true
disableImageZoom = true
disableImageOptimization = false
disableTextInHeader = true
defaultBackgroundImage = "img/background.webp"
defaultSocialImage = "img/social-image.webp"
smartTOC = true
smartTOCHideUnfocusedChildren = false
highlightCurrentMenuArea = true

# mainSections = ["section1", "section2"]
# robots = ""

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = false 
  showScrollToTop = true

[homepage]
  layout = "background"
  layoutBackgroundBlur = true 
  # homepageImage = "img/background.webp" 
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = false
  showSummary = true
  sharingLinks = false

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  cardView = true
  constrainItemsWidth = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"

[term]
  showHero = true
  heroStyle = "background"

[buymeacoffee]
  identifier = "insidemordecai"
  globalWidget = false
  globalWidgetMessage = ""
  globalWidgetColor = "#009BAD"
  globalWidgetPosition = "Right"
