# -- Theme Options --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
disableImageOptimization = false
defaultBackgroundImage = "img/background.jpg"

smartTOC = true
smartTOCHideUnfocusedChildren = false
highlightCurrentMenuArea = true

# mainSections = ["section1", "section2"]
# robots = ""

[header]
  layout = "fixed"

[footer]
  showCopyright = false
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  layoutBackgroundBlur = true
  homepageImage = "img/background.jpg" # used in: hero, and card
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = false
  showAuthorsBadges = false
  showWordCount = false
  showSummary = true
  sharingLinks = false

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = true
  constrainItemsWidth = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"

[term]
  showHero = true
  heroStyle = "background"

[firebase]
  # apiKey = "AIzaSyDCLuiQ-2mwwojhYV0lGEBPeDkqJNpL0A4"
  # authDomain = "insidemordecai.firebaseapp.com"
  # projectId = "insidemordecai"
  # storageBucket = "insidemordecai.appspot.com"
  # messagingSenderId = "228384505712"
  # appId = "1:228384505712:web:30019f365a2979a50259b5"
  # measurementId = "G-CZX2TB59D8"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
